# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

            - name: Sort imports with isort
              run: |
                  isort **/*.py
            - name: Format code with black
              run: |
                  black gymnasdicts tests
            - name: Lint with flake8
              run: |
                  flake8 gymnasdicts tests
            - name: Test with pytest
              run: |
                  pytest --cov=gymnasdicts --cov-fail-under=100 --cov-report=term-missing
            - name: Test with doctest
              run: |
                  pytest --doctest-modules gymnasdicts
            - name: Static typechecking with mypy
              run: |
                  mypy gymnasdicts tests
